### ISSUE TITLE
Unable to connect to camera in Android

### ISSUE THREAD

**Issue by rollsroyc3** [jwcao/opentok-titanium#1]
I am unable to connect to either cameraFront or cameraBack on Android. I am using an HTC M8 on 5.0.1. I see the other user that is a publisher it just does not connect to my camera and allow me to view myself. Here is the log info, please let me know if you need anything else:

```
[INFO] :   opentok createOpentokSession
[INFO] :   art: Thread[13,tid=29217,WaitingForJniOnLoad,Thread*=0xb8012528,peer=0x12c005c0,"KrollRuntimeThread"] recursive attempt to load library "/data/app/co.r3mobile.secondmd-2/lib/arm/libopentok.so"
[INFO] :   art: Thread[13,tid=29217,WaitingForJniOnLoad,Thread*=0xb8012528,peer=0x12c005c0,"KrollRuntimeThread"] recursive attempt to load library "/data/app/co.r3mobile.secondmd-2/lib/arm/libopentok.so"
[INFO] :   I/opentok-session: Checking hardware decoding support: HTC6525LVW
[WARN] :   CameraBase: An error occurred while connecting to camera: 0
[WARN] :   CameraBase: An error occurred while connecting to camera: 0
[WARN] :   CameraBase: An error occurred while connecting to camera: 0
[WARN] :   CameraBase: An error occurred while connecting to camera: 0
[WARN] :   CameraBase: An error occurred while connecting to camera: 0
[INFO] :   Camera2Mode: fail
[WARN] :   CameraBase: An error occurred while connecting to camera: 1
[ERROR] :  E/WEBRTC-JC: Failed to open Camera 0, Facing back, Orientation 90, skipping
[ERROR] :  E/WEBRTC-JC: java.lang.RuntimeException: Fail to connect to camera service
[ERROR] :  E/WEBRTC-JC:     at android.hardware.Camera.open(Camera.java:498)
[ERROR] :  E/WEBRTC-JC:     at org.webrtc.videoengine.VideoCaptureDeviceInfoAndroid.getDeviceInfo(VideoCaptureDeviceInfoAndroid.java:56)
[ERROR] :  E/WEBRTC-JC:     at com.opentok.android.Session.init(Native Method)
[ERROR] :  E/WEBRTC-JC:     at com.opentok.android.Session.<init>(Session.java:403)
[ERROR] :  E/WEBRTC-JC:     at com.tokbox.ti.opentok.SessionProxy.createSession(SessionProxy.java:167)
[ERROR] :  E/WEBRTC-JC:     at com.tokbox.ti.opentok.SessionProxy.handleCreationDict(SessionProxy.java:159)
[ERROR] :  E/WEBRTC-JC:     at org.appcelerator.kroll.KrollProxy.handleCreationArgs(KrollProxy.java:227)
[ERROR] :  E/WEBRTC-JC:     at com.tokbox.ti.opentok.SessionProxy.handleCreationArgs(SessionProxy.java:179)
[ERROR] :  E/WEBRTC-JC:     at org.appcelerator.kroll.KrollProxy.setupProxy(KrollProxy.java:135)
[ERROR] :  E/WEBRTC-JC:     at org.appcelerator.kroll.KrollProxy.createProxy(KrollProxy.java:143)
[ERROR] :  E/WEBRTC-JC:     at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[ERROR] :  E/WEBRTC-JC:     at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:62)
[ERROR] :  E/WEBRTC-JC:     at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:908)
[ERROR] :  E/WEBRTC-JC:     at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1131)
[ERROR] :  E/WEBRTC-JC:     at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:347)
[ERROR] :  E/WEBRTC-JC:     at android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] :  E/WEBRTC-JC:     at android.os.Looper.loop(Looper.java:155)
[ERROR] :  E/WEBRTC-JC:     at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
[WARN] :   CameraBase: An error occurred while connecting to camera: 1
[WARN] :   CameraBase: An error occurred while connecting to camera: 1
[WARN] :   CameraBase: An error occurred while connecting to camera: 1
[WARN] :   CameraBase: An error occurred while connecting to camera: 1
[INFO] :   Camera2Mode: fail
[ERROR] :  E/WEBRTC-JC: Failed to open Camera 1, Facing front, Orientation 270, skipping
[ERROR] :  E/WEBRTC-JC: java.lang.RuntimeException: Fail to connect to camera service
[ERROR] :  E/WEBRTC-JC:     at android.hardware.Camera.open(Camera.java:498)
[ERROR] :  E/WEBRTC-JC:     at org.webrtc.videoengine.VideoCaptureDeviceInfoAndroid.getDeviceInfo(VideoCaptureDeviceInfoAndroid.java:56)
[ERROR] :  E/WEBRTC-JC:     at com.opentok.android.Session.init(Native Method)
[ERROR] :  E/WEBRTC-JC:     at com.opentok.android.Session.<init>(Session.java:403)
[ERROR] :  E/WEBRTC-JC:     at com.tokbox.ti.opentok.SessionProxy.createSession(SessionProxy.java:167)
[ERROR] :  E/WEBRTC-JC:     at com.tokbox.ti.opentok.SessionProxy.handleCreationDict(SessionProxy.java:159)
[ERROR] :  E/WEBRTC-JC:     at org.appcelerator.kroll.KrollProxy.handleCreationArgs(KrollProxy.java:227)
[ERROR] :  E/WEBRTC-JC:     at com.tokbox.ti.opentok.SessionProxy.handleCreationArgs(SessionProxy.java:179)
[ERROR] :  E/WEBRTC-JC:     at org.appcelerator.kroll.KrollProxy.setupProxy(KrollProxy.java:135)
[ERROR] :  E/WEBRTC-JC:     at org.appcelerator.kroll.KrollProxy.createProxy(KrollProxy.java:143)
[ERROR] :  E/WEBRTC-JC:     at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[ERROR] :  E/WEBRTC-JC:     at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:62)
[ERROR] :  E/WEBRTC-JC:     at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:908)
[ERROR] :  E/WEBRTC-JC:     at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1131)
[ERROR] :  E/WEBRTC-JC:
[ERROR] :  E/WEBRTC-JC:     at android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] :  E/WEBRTC-JC:     at android.os.Looper.loop(Looper.java:155)
[ERROR] :  E/WEBRTC-JC:     at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
[ERROR] :  CaoOpentokModule: createSession : Created Session
[INFO] :   opentok connectSession
[INFO] :   CaoOpentokModule: OpentokAndroid SessionProxy connect : Connecting a session.
[INFO] :   I/opentok-session: Connecting to the session. SessionID: 2_MX40NTE4NDU0Mn5-MTQzMzM2ODI2MzY5Mn5Gb2ZUaEhKWVJ4aFhzRFdHTXR1NDJUaHl-fg Token: T1==cGFydG5lcl9pZD00NTE4NDU0MiZzaWc9ZWIyMTcyYWRiOGQ1YmY4Zjc4MDQyY2Y1MDU5YmVkYzM0ZTFhNjhkZTpyb2xlPXB1Ymxpc2hlciZzZXNzaW9uX2lkPTJfTVg0ME5URTRORFUwTW41LU1UUXpNek0yT0RJMk16WTVNbjVHYjJaVWFFaEtXVko0YUZoelJGZEhUWFIxTkRKVWFIbC1mZyZjcmVhdGVfdGltZT0xNDMzMzY4Mjg0Jm5vbmNlPTAuMDgzNzkxNDcwNDkzOTA2NDUmZXhwaXJlX3RpbWU9MTQzMzQ1NDY1NCZjb25uZWN0aW9uX2RhdGE9 ApiKey: 45184542
[INFO] :   I/opentok-session: Session is connected
[INFO] :   opentok sessionConnected
[INFO] :   CaoOpentokModule: OpentokAndroid SessionProxy publish : Publishing a stream.
[INFO] :   I/opentok-session: New session connection is created. ConnectionId: 05d004d3-34ac-4325-afc7-b518d00193ab
[INFO] :   I/opentok-session: New session stream is created. StreamId: b32636e1-f6a8-4261-94a6-a36d93589e00
[INFO] :   CaoOpentokModule: OpentokAndroid SessionProxy onSessionDidReceiveStream : Got a stream.
[INFO] :   I/opentok-publisher: Setting cameraId to 0
[INFO] :   I/opentok-publisher: Publisher has changed the camera position to: 0
[INFO] :   CaoOpentokModule: AndroidOpentok PublisherProxy onPublisherChangedCamera : onPublisherChangedCamera event fired
[INFO] :   CaoOpentokModule: AndroidOpentok PublisherProxy createView : Creating a new OpentokViewProxy
[INFO] :   CaoOpentokModule: OpentokView : androidView is not null. Trying to set the native view
[INFO] :   CaoOpentokModule: AndroidOpentok View : Set the native view and camera started.
[INFO] :   CaoOpentokModule: OpentokAndroid ViewProxy createView : have the view, returning it
[INFO] :   CaoOpentokModule: AndroidOpentok processProperties : processProperties called.
[INFO] :   I/opentok-session: Starting a Publisher streaming to the session
[WARN] :   CameraBase: An error occurred while connecting to camera: 0
[WARN] :   CameraBase: An error occurred while connecting to camera: 0
[WARN] :   CameraBase: An error occurred while connecting to camera: 0
[WARN] :   CameraBase: An error occurred while connecting to camera: 0
[WARN] :   CameraBase: An error occurred while connecting to camera: 0
[INFO] :   Camera2Mode: fail
[ERROR] :  E/opentok-videocapturer: The camera is in use by another app
[INFO] :   I/opentok-publisher: Camera device has failed
[ERROR] :  E/opentok-videocapturer: java.lang.RuntimeException: Fail to connect to camera service
[ERROR] :  E/opentok-videocapturer:     at android.hardware.Camera.open(Camera.java:498)
[ERROR] :  E/opentok-videocapturer:     at com.opentok.android.DefaultVideoCapturer.init(DefaultVideoCapturer.java:84)
[ERROR] :  CaoOpentokModule: AndroidOpentok PublisherProxy onCameraError : The camera of the device has failed.
[INFO] :   opentok streamCreated
[INFO] :   CaoOpentokModule: OpentokAndroid SessionProxy subscribe : Subscribing to a stream.
[INFO] :   CaoOpentokModule: OpentokView : androidView is not null. Trying to set the native view
[INFO] :   CaoOpentokModule: AndroidOpentok View : Set the native view and camera started.
[INFO] :   CaoOpentokModule: OpentokAndroid ViewProxy createView : have the view, returning it
[INFO] :   CaoOpentokModule: AndroidOpentok processProperties : processProperties called.
[INFO] :   I/opentok-session: Start subscribing to streamId: b32636e1-f6a8-4261-94a6-a36d93589e00 in the session
[INFO] :   I/opentok-subscriberkit: Subscriber with streamId: b32636e1-f6a8-4261-94a6-a36d93589e00 is connected
[ERROR] :  AudioRecord: AudioFlinger could not create record track, status: -1
[INFO] :   CaoOpentokModule: AndroidOpentok SubscriberProxy onConnected : We fired the event for a subscriber connecting
[WARN] :   AudioTrack: dead IAudioTrack, PCM, creating a new one from obtainBuffer()
[INFO] :   I/opentok-defaultaudiodevice: Audio capture is not initialized 44100
[WARN] :   AudioTrack: dead IAudioTrack, PCM, creating a new one from obtainBuffer()
[ERROR] :  AudioTrack: detected illegal retrograde motion by the server: mServer advanced by -17707
[ERROR] :  E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -1.
[ERROR] :  E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
[WARN] :   AudioSystem: ioConfigChanged() closing unknown output! 2190
```

**Comment by jwcao** [comment]
It looks like it's trying to connect to both the front and the back camera but fails for both. I would try downloading the OpenTok demo for Android and see if you can get that to work (so take Titanium out of the equation). Or see if you can get the Titanium module to work with a different Android device.

**Comment by rollsroyc3** [comment]
OK, so I downloaded the demo off the Play Store OpenTokRTC and it worked fine. I then tried my app with the OpenTok module on a moto X 1st generation and had the same issue. I could see the other user but not myself. Have you run into any of these issues with Android? Do I need to set the camera permission manually?

**Comment by jwcao** [comment]
I haven't run into any issues with Android for quite a while. We used to do the old flash version of the OpenTok sdk, and we had tons of issues with that, but once I updated to WebRTC Android has worked great. The example code I have in the readme is basically what I'm doing in my app, just with some callbacks stripped out. I don't have much time to investigate it today, but I'll try and think on what might be causing the issue for you.

**Comment by rollsroyc3** [comment]
OK, so I tried to add the camera permission but that did not seem to do it. I will also be spending some time in the next few days digging into the code a little more. Will let you know..

**Comment by jwcao** [comment]
Have you just been building it yourself for Android, or did you try the dist I have on the releases page? If you haven't tried both, maybe see if the other will work for you.

**Comment by rollsroyc3** [comment]
Just tried building from source, same issue. I plan on digging into the code more this weekend.

**Comment by rollsroyc3** [comment]
OK, so I finally got it working. I can submit a pr but essentially all I had to do was include the camera permission in timodule.xml before building. Here is the snippet needed. Thanks again for all your help.

```
<android xmlns:android="http://schemas.android.com/apk/res/android">
        <manifest>
            <uses-permission android:name="android.permission.CAMERA"/>
        </manifest>
    </android>
```

**Comment by jwcao** [comment]
Ah, yeah. You definitely need to do that. :) I'll add to the readme that you need to add the appropriate permissions to timodule.xml. That was an oversight on my part. Thanks for getting it figured out.
